// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Pechi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240122095805_initialize")]
    partial class initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pechi.DataBase.Agregati", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Название_агрегата")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Тип")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Технологические_агрегаты");
                });

            modelBuilder.Entity("Pechi.DataBase.Litsa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Отчество")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ответственные_лица");
                });

            modelBuilder.Entity("Pechi.DataBase.Prostoi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Агрегата")
                        .HasColumnType("int");

                    b.Property<int>("ID_Лица")
                        .HasColumnType("int");

                    b.Property<int>("ID_Типа")
                        .HasColumnType("int");

                    b.Property<string>("Время_простоя_план")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Время_простоя_факт")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Дата_начала_простоя")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Дата_окончания_простоя")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Описание")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Простои");
                });

            modelBuilder.Entity("Pechi.DataBase.RegistrationData", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Login");

                    b.ToTable("Регистрация");
                });

            modelBuilder.Entity("Pechi.DataBase.Tipi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Название_простоя")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Описание")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Типы_простоев");
                });
#pragma warning restore 612, 618
        }
    }
}
